<<<<<<< HEAD
server:
  port: 80
  servlet:
    context-path: /novel

spring:
  datasource:
    name: novel
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      url: jdbc:mysql://localhost:3306/novel?useUnicode=true&serverTimezone=UTC&characterEncoding=UTF-8&useSSL=true&allowMultiQueries=true
      username: root
      password: 123
      driver-class-name: com.mysql.cj.jdbc.Driver
      initial-size: 1
      min-idle: 1
      max-active: 20
      max-wait: 60000

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    encoding: UTF-8
    servlet:
      content-type: text/html; charset=utf-8
    cache: false
  resources:
    chain:
      strategy:
        content:
          enabled: true
          paths:
          - /**

mybatis:
  type-aliases-package: com.entity
  mapper-locations:
=======
server:
<<<<<<< HEAD
  port: 80
=======
  port: 10080
>>>>>>> second commit
  servlet:
    context-path: /novel

spring:
  datasource:
    name: novel
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      url: jdbc:mysql://localhost:3306/novel?useUnicode=true&serverTimezone=UTC&characterEncoding=UTF-8&useSSL=true&allowMultiQueries=true
      username: root
<<<<<<< HEAD
      password: 123
=======
      password: root
>>>>>>> second commit
      driver-class-name: com.mysql.cj.jdbc.Driver
      initial-size: 1
      min-idle: 1
      max-active: 20
      max-wait: 60000

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    encoding: UTF-8
    servlet:
      content-type: text/html; charset=utf-8
    cache: false
  resources:
    chain:
      strategy:
        content:
          enabled: true
          paths:
          - /**

mybatis:
  type-aliases-package: com.entity
  mapper-locations:
>>>>>>> second commit
  - classpath:mapper/*.xml